name: .NET Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install .NET Framework 4.8 SDK
      run: |
        choco install dotnetfx --version=4.8.0.0

    - name: Setup NuGet
      run: |
        nuget restore ./ProxyPin/BoratRat.csproj

    - name: Build
      run: dotnet build ./ProxyPin/BoratRat.csproj --configuration Release
