name: .NET Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '4.8.x'

    - name: Install .NET Framework 4.8 SDK
      run: |
        choco install dotnetfx --version=4.8.0.0

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release
